### ISSUE TITLE
Aggregate Data

### ISSUE THREAD

**Issue by Paropt** [BigData712/aws-stack#2]
Data for each year is stored in several CSV files but came with .sql files to create and load a database with all of the information.  Instead we can load all of the data, join the specific data that we need, and export them into a .json file so that we can load it into AWS.

**Comment by Paropt** [comment]
https://search-crimesearch2ad9-q7cnd4taraup-lon7amfupvzamt45h7gjtdk7c4.us-east-1.es.amazonaws.com/_dashboards/app/login?

**Comment by eurekesh** [comment]
Details on discord, data has been aggregated and accessible. [https://cc-api-wav6.onrender.com/](endpoint url)
